// Job description generation and export.
import { fmt, unitLabel } from './comp.js';
import { LEVELS } from '../data/roles.js';
import { findFunction } from '../data/functions.js';

const lines = (arr, bullet = '•') => arr.map((x) => `${bullet} ${x}`).join('\n');

// Full JD as structured sections; `edits` (from Edit JD) override generated sections.
export function buildJd(role, bm, filters, settings, edits = {}) {
  const loc = bm.location; const ind = bm.industry; const fn = findFunction(role.fn);
  const base = {
    title: role.title,
    meta: `${LEVELS[role.level]} (${role.level}) · ${role.family} · ${role.expMin}–${role.expMax === 99 ? '+' : role.expMax} years · ${loc.name} · ${ind.groupName} › ${ind.name}`,
    knowledgeLabel: fn.knowledgeLabel,
    summary: role.purpose,
    responsibilities: role.responsibilities,
    skills: role.skills,
    knowledge: role.knowledge,
    preferred: role.preferred,
    education: role.education,
    compensation: `Market reference ${fmt(bm.ref, filters)} (range ${fmt(bm.low, filters)} – ${fmt(bm.high, filters)}); recommended hiring range ${fmt(bm.hireLow, filters)} – ${fmt(bm.hireHigh, filters)} (${unitLabel(filters)}) · ${bm.location.name} · ${bm.industry.groupName} › ${bm.industry.name}, ${settings.dataAsOf}.`,
    about: `Future Factor 360 partners with global organisations to build and scale capability centers in India. This role sits in the ${fn.name} function of a client center in the ${ind.name} sector and offers exposure to global stakeholders, cross-functional teams and enterprise-scale ways of working.`,
  };
  return { ...base, ...edits };
}

export function jdToText(jd) {
  return [
    jd.title.toUpperCase(), jd.meta, '',
    'ABOUT THE OPPORTUNITY', jd.about, '',
    'ROLE PURPOSE', jd.summary, '',
    'KEY RESPONSIBILITIES', lines(jd.responsibilities), '',
    'CORE SKILLS', lines(jd.skills), '',
    (jd.knowledgeLabel || 'Domain knowledge').toUpperCase(), lines(jd.knowledge), '',
    'PREFERRED EXPERIENCE', lines(jd.preferred), '',
    'EDUCATION', jd.education, '',
    'COMPENSATION GUIDANCE (INTERNAL)', jd.compensation, '',
    'Generated by Future Factor 360 · Talent Market Intelligence',
  ].join('\n');
}

export function jdToMarkdown(jd) {
  return [
    `# ${jd.title}`, `_${jd.meta}_`, '',
    '## About the opportunity', jd.about, '',
    '## Role purpose', jd.summary, '',
    '## Key responsibilities', lines(jd.responsibilities, '-'), '',
    '## Core skills', lines(jd.skills, '-'), '',
    `## ${jd.knowledgeLabel || 'Domain knowledge'}`, lines(jd.knowledge, '-'), '',
    '## Preferred experience', lines(jd.preferred, '-'), '',
    '## Education', jd.education, '',
    '## Compensation guidance (internal)', jd.compensation, '',
    '_Generated by Future Factor 360 · Talent Market Intelligence_',
  ].join('\n');
}

export function download(filename, content, type = 'text/plain') {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a'); a.href = url; a.download = filename; document.body.appendChild(a); a.click(); a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
